CREATE TABLE `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `openid` varchar(100) NOT NULL,
  `nickname` varchar(100) DEFAULT NULL,
  `signature` varchar(255) DEFAULT '',
  `avatar_url` varchar(500) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `_openid` varchar(64) NOT NULL DEFAULT '',
  `school` varchar(100) DEFAULT '' COMMENT '学校',
  `major` varchar(100) DEFAULT '' COMMENT '专业',
  `grade` varchar(50) DEFAULT '' COMMENT '年级',
  `account_status` varchar(20) NOT NULL DEFAULT 'active',
  `account_ban_reason` varchar(255) DEFAULT NULL,
  `account_banned_until` datetime DEFAULT NULL,
  `note_status` varchar(20) NOT NULL DEFAULT 'active',
  `note_ban_reason` varchar(255) DEFAULT NULL,
  `note_banned_until` datetime DEFAULT NULL,
  `share_status` varchar(20) NOT NULL DEFAULT 'active',
  `share_ban_reason` varchar(255) DEFAULT NULL,
  `share_banned_until` datetime DEFAULT NULL,
  `avatar_status` varchar(20) NOT NULL DEFAULT 'active',
  `avatar_ban_reason` varchar(255) DEFAULT NULL,
  `avatar_banned_until` datetime DEFAULT NULL,
  `signature_status` varchar(20) NOT NULL DEFAULT 'active',
  `signature_ban_reason` varchar(255) DEFAULT NULL,
  `signature_banned_until` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `openid` (`openid`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb3;

